name: current
description: A simple yet powerful state management library for Flutter. Keeps your widget build methods clean, with ZERO dependencies on other packages.
version: 3.0.0-beta-6
homepage: https://github.com/thirdversion/flutter_current
topics: [state-management, validation]
issue_tracker: https://github.com/thirdversion/flutter_current/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
