import 'dart:async';

import 'package:current/current.dart';
import 'package:current/src/current_exceptions.dart';
import 'package:flutter/material.dart';

/// A TextEditingController that is bound to a CurrentProperty.
///
/// Should apply the [CurrentTextControllersLifecycleMixin] mixin to the State of your Widget to manage the lifecycle of the controller and ensure it is properly disposed of.
///
/// Use the factory contructors to create a new instance.
///
/// [CurrentTextController.string], [CurrentTextController.nullableString],
///
/// [CurrentTextController.integer], [CurrentTextController.nullableInteger],
///
/// [CurrentTextController.date], and [CurrentTextController.nullableDate]
///
/// These are provided for convenience when working with common types, but you can also use [CurrentTextController.of] to create a controller for any type.
///
/// When using [CurrentTextController.of], you must provide the fromString and [asString] functions in the [bind] method to specify how to parse the text into the property's type and how to display the property's value as text.
///
/// It listens for changes to the property and updates the text accordingly, and also updates the property when the text changes.
/// You MUST call [bind] to configure the controller. If you do not, the controller will simply act as a normal [TextEditingController].
///
/// When used together with [CurrentFieldValidation], the controller can also:
/// - mark a field as touched when the user edits text
/// - surface parse failures as validation metadata
/// - surface required-value failures for non-nullable fields without defaults
/// - revalidate when the bound property changes externally
///
/// Controller-generated validation messages are localizable through
/// [CurrentTextControllerValidationMessages]. This is important because parse
/// failures and required-value failures are generated by the controller rather
/// than by property-specific validator rules.
///
/// Example usage:
///
///
/// ```dart
///
/// class MyWidgetViewModel extends CurrentViewModel {
///   final name = CurrentStringProperty();
///   final age = CurrentIntProperty();
///   final departureDate = CurrentNullableDateTimeProperty();
///
///   @override
///   Iterable<CurrentProperty> get currentProps => [name, age, departureDate];
/// }
///
/// class _MyWidgetState extends CurrentState<_MyWidgetState, MyWidgetViewModel> with CurrentTextControllersLifecycleMixin {
///
///   final nameController = CurrentTextController.string();
///   final ageController = CurrentTextController.integer();
///   final departureDateController = CurrentTextController.nullableDate();
///
///   @override
///   void bindCurrentControllers() {
///     nameController.bindString(
///       property: viewModel.name,
///       lifecycleProvider: this,
///     );
///     ageController.bindInt(
///       property: viewModel.age,
///       lifecycleProvider: this,
///       defaultValue: 0,
///     );
///     departureDateController.bindDateTime(
///       property: viewModel.departureDate,
///       lifecycleProvider: this,
///       fromString: DateTime.parse,
///     );
///   }
///
///   @override
///   void dispose() {
///     nameController.dispose();
///     ageController.dispose();
///     departureDateController.dispose();
///     super.dispose();
///   }
///
///   @override
///   Widget build(BuildContext context) {
///     return Column(
///       children: [
///         TextField(controller: nameController),
///         TextField(controller: ageController),
///         TextField(controller: departureDateController),
///       ],
///     );
///   }
/// }
/// ```
///
typedef CurrentTextControllerRequiredValueErrorBuilder = String? Function();
typedef CurrentTextControllerInvalidValueErrorBuilder = String? Function(
  String text,
);

/// Supplies controller-generated validation messages for [CurrentTextController].
///
/// These messages are only used when a [CurrentFieldValidation] is attached to a
/// controller and the controller itself needs to surface a validation
/// problem that did not come from the property's validator rules.
///
/// Typical examples include generic messages such as "this value is required"
/// or "this input could not be parsed".
///
/// Some concrete scenarios include:
/// - the user entering text that fails parsing for a non-String property
/// - the user clearing a non-nullable field that does not have a default value
///
/// This type exists so library consumers can localize those controller-level
/// messages instead of receiving hardcoded English output from the library.
///
/// You can either:
/// - override [CurrentTextController.defaultValidationMessages] once for the app
/// - pass a per-binding [validationMessages] value to [bind], [bindString],
///   [bindInt], or [bindDateTime]
///
/// The builders are called the moment the validation problem occurs, which
/// allows closures to read localized values dynamically.
///
/// ## Example
///
/// ```dart
/// ageController.bindInt(
///   property: viewModel.age,
///   lifecycleProvider: this,
///   validation: viewModel.ageValidation,
///   validationMessages: CurrentTextControllerValidationMessages(
///     requiredValueErrorBuilder: () => 'Entrez une valeur',
///     invalidValueErrorBuilder: (_) => 'Valeur incorrecte',
///   ),
/// );
/// ```
final class CurrentTextControllerValidationMessages {
  /// Builder used when a non-nullable field is cleared and no default value is
  /// available.
  ///
  /// Returning `null` suppresses the controller-generated required-value error.
  final CurrentTextControllerRequiredValueErrorBuilder?
      requiredValueErrorBuilder;

  /// Builder used when text cannot be parsed into the target property type.
  ///
  /// The rejected text is provided so callers can vary the message if needed.
  /// Returning `null` suppresses the controller-generated parse error.
  final CurrentTextControllerInvalidValueErrorBuilder? invalidValueErrorBuilder;

  /// Creates a set of controller-generated validation message builders.
  const CurrentTextControllerValidationMessages({
    this.requiredValueErrorBuilder,
    this.invalidValueErrorBuilder,
  });

  /// Returns the required-value message, if configured.
  String? requiredValueErrorText() => requiredValueErrorBuilder?.call();

  /// Returns the invalid-value message for the provided [text], if configured.
  String? invalidValueErrorText(String text) =>
      invalidValueErrorBuilder?.call(text);
}

/// A [TextEditingController] that keeps a [CurrentProperty] and a text field in
/// sync.
///
/// [CurrentTextController] is intended to remove the repetitive plumbing around
/// reading, formatting, parsing, and writing text-field state when working with
/// [CurrentProperty] values.
///
/// The controller supports:
/// - String bindings to keep controller text in sync with the property's value
/// - non-String bindings through a [fromString] parser
/// - custom display formatting through [asString]
/// - default values for cleared non-nullable fields
/// - optional validation through [CurrentFieldValidation]
/// - localized controller-generated validation messages through
///   [CurrentTextControllerValidationMessages]
///
/// This controller does not replace your field validators. Instead, it fills in
/// the gap between raw text editing and property-level validation by surfacing
/// validation metadata for failures that occur before property-level validation,
/// such as parse errors.
final class CurrentTextController<T> extends TextEditingController {
  /// Global default messages used when a binding does not provide
  /// [CurrentTextControllerValidationMessages] explicitly.
  ///
  /// Can be replaced at startup to provide localized controller-generated
  /// validation messages across the app.
  ///
  /// These defaults are only used for controller-originated validation errors,
  /// such as parse failures and required-value failures. Property validator
  /// rules remain fully controlled by the consumer.
  ///
  /// ## Example
  ///
  /// ```dart
  /// CurrentTextController.defaultValidationMessages =
  ///     CurrentTextControllerValidationMessages(
  ///   requiredValueErrorBuilder: () => '値を入力してください',
  ///   invalidValueErrorBuilder: (_) => '無効な値です',
  /// );
  /// ```
  static CurrentTextControllerValidationMessages defaultValidationMessages =
      CurrentTextControllerValidationMessages(
    requiredValueErrorBuilder: () => 'A value is required.',
    invalidValueErrorBuilder: (_) => 'Invalid value.',
  );

  /// The [CurrentProperty] that this controller is bound to. This will be set during initialization in the [bind] method.
  ///
  CurrentProperty<T?>? _property;
  CurrentProperty<T?> get property {
    final boundProperty = _property;

    if (boundProperty == null) {
      throw CurrentTextControllerNotInitializedException<T>();
    }

    return boundProperty;
  }

  /// A function that parses a string into the type of the [CurrentProperty]. This is used to update the property's value when the text changes. This will be set during initialization in the [bind] method. If the [CurrentProperty] is of type String, this function can be omitted and the controller will simply use the text as the property's value.
  ///
  T Function(String text)? _fromString;
  T Function(String text)? get fromString => _fromString;

  /// A function that converts the [CurrentProperty]'s value into a string for display in the text field. This will be set during initialization in the [bind] method. If not provided, it will default to using the property's value's toString() method, or an empty string if the property's value is null.
  ///
  String? Function(T? propertyValue)? _asString;
  String? Function(T? propertyValue)? get asString => _asString;

  /// Optional validation helper associated with the bound [CurrentProperty].
  ///
  /// When provided, this controller will mark the field as touched during user
  /// edits, surface rejected text as validation metadata, and keep the
  /// validation state synchronized with successful property updates.
  ///
  /// This validator must target the same [CurrentProperty] instance that is
  /// passed to [bind]. If it does not, [bind] throws an [ArgumentError].
  CurrentFieldValidation<dynamic>? _validation;
  CurrentFieldValidation<dynamic>? get validation => _validation;

  /// Optional per-binding controller-generated validation messages.
  ///
  /// When null, [defaultValidationMessages] is used.
  ///
  /// Use this when a single field requires different messages than the app-wide
  /// defaults, or when localized strings need to come from a widget-level
  /// context.
  CurrentTextControllerValidationMessages? _validationMessages;
  CurrentTextControllerValidationMessages? get validationMessages =>
      _validationMessages;

  /// An optional default value to use when parsing the text if the [fromString] function fails to parse the text. This is only used for non-String properties. If the [CurrentProperty] is of type String, this can be omitted since parsing will not be performed.
  ///
  StreamSubscription? _subscription;

  /// An optional default value to use when parsing the text if the [fromString] function fails to parse the text. This is only used for non-String properties. If the [CurrentProperty] is of type String, this can be omitted since parsing will not be performed.
  ///
  T? _defaultValue;
  T? get defaultValue => _defaultValue;

  bool get _isNullable => null is T;

  bool _hasDefaultValue = false;
  bool _isSyncingText = false;
  bool _treatTextAsStringValue = false;

  CurrentTextControllersLifecycleMixin? _lifecycleProvider;

  CurrentTextController._() {
    addListener(_handleTextChanged);
  }

  /// Factory constructor to create a CurrentTextController for a String property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindString]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<String> string() =>
      CurrentTextController<String>._();

  /// Factory constructor to create a CurrentTextController for a nullable String  property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindString]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<String?> nullableString() =>
      CurrentTextController<String?>._();

  /// Factory constructor to create a CurrentTextController for an integer property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindInt]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<int> integer() => CurrentTextController<int>._();

  /// Factory constructor to create a CurrentTextController for a nullable integer property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindInt]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<int?> nullableInteger() =>
      CurrentTextController<int?>._();

  /// Factory constructor to create a CurrentTextController for a DateTime property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindDateTime]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<DateTime> date() =>
      CurrentTextController<DateTime>._();

  /// Factory constructor to create a CurrentTextController for a nullable DateTime property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindDateTime]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<DateTime?> nullableDate() =>
      CurrentTextController<DateTime?>._();

  /// Factory constructor to create a CurrentTextController for a type specified by the generic parameter [T].
  ///
  /// **IMPORTANT**: You still must call either the [bind]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<T> of<T>() => CurrentTextController<T>._();

  /// Initializes the CurrentTextController by binding it to a CurrentProperty and providing necessary configuration for parsing and displaying the property's value.
  ///
  /// If the CurrentProperty is not of type String, you must provide a fromString function to parse the text into the property's type.
  ///
  /// If it is a Non-Nullable non-String type, you can optionally provide a
  /// [defaultValue]. When the user clears the text field, the controller will
  /// use that explicit default value instead of leaving the property unchanged.
  /// Invalid non-empty text does not throw and does not update the property
  /// until parsing succeeds.
  ///
  /// If the CurrentProperty is of type String, you can omit the fromString function and the controller will simply use the text as the property's value. In this case, providing a defaultValue is not necessary since parsing will not be performed.
  ///
  /// The asString function is optional, but can be used to customize how the property's value is displayed in the text field. If not provided, it will default to using the property's value's toString() method, or an empty string if the property's value is null.
  ///
  /// If [validation] is provided, [validationMessages] can be used to override
  /// the controller-generated validation messages for this binding. This is the
  /// preferred way to localize parse-failure and required-value messages.
  ///
  /// Validation behavior when [validation] is provided:
  /// - user edits mark the field as touched
  /// - parse failures set controller-generated validation metadata
  /// - successful updates re-run the validator against the new property value
  /// - external property changes re-sync the text and revalidate
  ///
  /// If [validationMessages] is omitted, [defaultValidationMessages] is used.
  ///
  /// If a [validation] is supplied for a different property than [property], an
  /// [ArgumentError] is thrown.
  ///
  void bind({
    required CurrentProperty<T?> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    T Function(String text)? fromString,
    String? Function(T? propertyValue)? asString,
    T? defaultValue,
    CurrentFieldValidation<dynamic>? validation,
    CurrentTextControllerValidationMessages? validationMessages,
  }) {
    final treatTextAsStringValue = _isStringProperty(property);

    if (!treatTextAsStringValue && fromString == null) {
      throw ArgumentError.value(
        fromString,
        'fromString',
        'A fromString function is required for non-String CurrentTextController bindings.',
      );
    }

    if (validation != null && !identical(validation.property, property)) {
      throw ArgumentError.value(
        validation,
        'validation',
        'The provided CurrentFieldValidation must target the same CurrentProperty bound to this controller.',
      );
    }

    if (_matchesBinding(
      property: property,
      lifecycleProvider: lifecycleProvider,
      fromString: fromString,
      asString: asString,
      defaultValue: defaultValue,
      treatTextAsStringValue: treatTextAsStringValue,
      validation: validation,
      validationMessages: validationMessages,
    )) {
      return;
    }

    _subscription?.cancel();

    _property = property;
    _fromString = fromString;
    _asString = asString;
    _defaultValue = defaultValue;
    _hasDefaultValue = !_isNullable && defaultValue != null;
    _treatTextAsStringValue = treatTextAsStringValue;
    _lifecycleProvider = lifecycleProvider;
    _validation = validation;
    _validationMessages = validationMessages;

    _subscription =
        property.viewModel.addStateChangedListener<CurrentStateChanged>(
      (_) {
        _setText();
        _validation?.validate();
      },
      filter: (event) =>
          event.sourceHashCode == property.sourceHashCode &&
          event is! CurrentValidationChanged,
    );

    _setText();
  }

  /// A convenience method for initializing the controller with properties based on [CurrentProperty<String>]. This is equivalent to calling [bind] with fromString and asString configured for String properties.
  /// If the CurrentProperty is not of type String, this method will throw an exception.
  ///
  /// See [bind] for details on [validation] and [validationMessages].
  ///
  void bindString({
    required CurrentProperty<T> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    String? Function(T? propertyValue)? asString,
    CurrentFieldValidation<T>? validation,
    CurrentTextControllerValidationMessages? validationMessages,
  }) {
    (bool isValidType, List<Type> validTypes) validateType(
        CurrentProperty property) {
      final validTypes = [
        CurrentProperty<String>,
        CurrentProperty<String?>,
        CurrentStringProperty,
        CurrentNullableStringProperty
      ];

      // This is done in a verbose way, duplicating the list (unfortunately) to ensure type check safety,
      // guarding against Darts reified generics. Simply checking via `validTypes.any((type) => property.runtimeType == type)`
      // is not guaranteed to behave correctly due to possible type erasure.
      if (property is! CurrentProperty<String> &&
          property is! CurrentProperty<String?> &&
          property is! CurrentStringProperty &&
          property is! CurrentNullableStringProperty) {
        return (false, validTypes);
      }
      return (true, validTypes);
    }

    if (validateType(property) case (false, final validTypes)) {
      throw CurrentTextControllerCurrentPropertyTypeException(
        property,
        'stringController',
        validTypes,
      );
    }

    bind(
      property: property,
      lifecycleProvider: lifecycleProvider,
      asString: asString,
      validation: validation,
      validationMessages: validationMessages,
    );
  }

  /// A convenience method for initializing the controller with properties based on [CurrentProperty<int>]. This is equivalent to calling [bind] with fromString and asString configured for int properties.
  /// If the CurrentProperty is not of type int, this method will throw an exception.
  ///
  /// If [fromString] is omitted, [int.parse] is used.
  ///
  /// See [bind] for details on [defaultValue], [validation], and
  /// [validationMessages].
  ///
  void bindInt({
    required CurrentProperty<T> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    T Function(String text)? fromString,
    String? Function(T? propertyValue)? asString,
    T? defaultValue,
    CurrentFieldValidation<T>? validation,
    CurrentTextControllerValidationMessages? validationMessages,
  }) {
    (bool isValidType, List<Type> validTypes) validateType(
        CurrentProperty property) {
      final validTypes = [
        CurrentProperty<int>,
        CurrentProperty<int?>,
        CurrentIntProperty,
        CurrentNullableIntProperty
      ];

      // This is done in a verbose way, duplicating the list (unfortunately) to ensure type check safety,
      // guarding against Darts reified generics. Simply checking via `validTypes.any((type) => property.runtimeType == type)`
      // is not guaranteed to behave correctly due to possible type erasure.
      if (property is! CurrentProperty<int> &&
          property is! CurrentProperty<int?> &&
          property is! CurrentIntProperty &&
          property is! CurrentNullableIntProperty) {
        return (false, validTypes);
      }
      return (true, validTypes);
    }

    if (validateType(property) case (false, final validTypes)) {
      throw CurrentTextControllerCurrentPropertyTypeException(
        property,
        'intController',
        validTypes,
      );
    }

    bind(
      property: property,
      lifecycleProvider: lifecycleProvider,
      fromString: fromString ?? (text) => int.parse(text) as T,
      asString: asString,
      defaultValue: defaultValue,
      validation: validation,
      validationMessages: validationMessages,
    );
  }

  /// A convenience method for initializing the controller with properties based on [CurrentProperty<DateTime>]. This is equivalent to calling [bind] with fromString and asString configured for DateTime properties.
  /// The [property] must be of type [CurrentProperty<DateTime>], [CurrentDateTimeProperty], or [CurrentNullableDateTimeProperty]. If it is not, this method will throw an exception.
  ///
  /// See [bind] for details on [validation] and [validationMessages].
  ///
  void bindDateTime({
    required CurrentProperty<T> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    required T Function(String text) fromString,
    String? Function(T? propertyValue)? asString,
    T? defaultValue,
    CurrentFieldValidation<T>? validation,
    CurrentTextControllerValidationMessages? validationMessages,
  }) {
    (bool isValidType, List<Type> validTypes) validateType(
        CurrentProperty property) {
      final validTypes = [
        CurrentProperty<DateTime>,
        CurrentProperty<DateTime?>,
        CurrentDateTimeProperty,
        CurrentNullableDateTimeProperty
      ];

      // This is done in a verbose way, duplicating the list (unfortunately) to ensure type check safety,
      // guarding against Darts reified generics. Simply checking via `validTypes.any((type) => property.runtimeType == type)`
      // is not guaranteed to behave correctly due to possible type erasure.
      if (property is! CurrentProperty<DateTime> &&
          property is! CurrentProperty<DateTime?> &&
          property is! CurrentDateTimeProperty &&
          property is! CurrentNullableDateTimeProperty) {
        return (false, validTypes);
      }
      return (true, validTypes);
    }

    if (validateType(property) case (false, final validTypes)) {
      throw CurrentTextControllerCurrentPropertyTypeException(
        property,
        'dateController',
        validTypes,
      );
    }

    bind(
      property: property,
      lifecycleProvider: lifecycleProvider,
      fromString: fromString,
      asString: asString ??
          (propertyValue) =>
              (propertyValue as DateTime?)?.toIso8601String() ?? '',
      defaultValue: defaultValue,
      validation: validation,
      validationMessages: validationMessages,
    );
  }

  void _setText({bool selectAll = false}) {
    final boundProperty = _property;

    if (boundProperty == null) {
      return;
    }

    final nextText = _asString?.call(boundProperty.value) ??
        boundProperty.value?.toString() ??
        '';

    if (nextText == text) {
      return;
    }

    _isSyncingText = true;

    try {
      value = TextEditingValue(
        text: nextText,
        selection: selectAll && nextText.isNotEmpty
            ? TextSelection(baseOffset: 0, extentOffset: nextText.length)
            : TextSelection.collapsed(offset: nextText.length),
      );
    } finally {
      _isSyncingText = false;
    }
  }

  void _handleTextChanged() {
    final boundProperty = _property;

    if (_isSyncingText || boundProperty == null) {
      return;
    }

    _validation?.markTouched();

    final parseResult = _tryParseText(text);

    if (!parseResult.shouldUpdate &&
        text.isEmpty &&
        !_isNullable &&
        !_hasDefaultValue) {
      _setControllerValidationError(
        _resolvedValidationMessages.requiredValueErrorText(),
      );
      _setText(selectAll: true);
      return;
    }

    if (!parseResult.shouldUpdate) {
      _setControllerValidationError(
        _resolvedValidationMessages.invalidValueErrorText(text),
      );
      return;
    }

    if (parseResult.value == boundProperty.value) {
      _validation?.validate(markTouched: true);
      return;
    }

    boundProperty.value = parseResult.value;
    _validation?.validate(markTouched: true);
  }

  ({bool shouldUpdate, T? value}) _tryParseText(String text) {
    if (_treatTextAsStringValue) {
      if (text.isEmpty && _isNullable) {
        return (shouldUpdate: true, value: null);
      }

      return (shouldUpdate: true, value: text as T);
    }

    if (text.isEmpty) {
      if (_isNullable) {
        return (shouldUpdate: true, value: null);
      }

      if (_hasDefaultValue) {
        return (shouldUpdate: true, value: _defaultValue);
      }

      return (shouldUpdate: false, value: null);
    }

    if (_fromString == null) {
      return (shouldUpdate: false, value: null);
    }

    try {
      return (shouldUpdate: true, value: _fromString!(text));
    } catch (_) {
      return (shouldUpdate: false, value: null);
    }
  }

  bool _isStringProperty(CurrentProperty property) {
    return property is CurrentProperty<String> ||
        property is CurrentProperty<String?> ||
        property is CurrentStringProperty ||
        property is CurrentNullableStringProperty;
  }

  bool _matchesBinding({
    required CurrentProperty<T?> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    required T Function(String text)? fromString,
    required String? Function(T? propertyValue)? asString,
    required T? defaultValue,
    required bool treatTextAsStringValue,
    required CurrentFieldValidation<dynamic>? validation,
    required CurrentTextControllerValidationMessages? validationMessages,
  }) {
    return identical(_property, property) &&
        identical(_lifecycleProvider, lifecycleProvider) &&
        identical(_fromString, fromString) &&
        identical(_asString, asString) &&
        identical(_validation, validation) &&
        identical(_validationMessages, validationMessages) &&
        _defaultValue == defaultValue &&
        _hasDefaultValue == (!_isNullable && defaultValue != null) &&
        _treatTextAsStringValue == treatTextAsStringValue;
  }

  CurrentTextControllerValidationMessages get _resolvedValidationMessages =>
      _validationMessages ?? defaultValidationMessages;

  void _setControllerValidationError(String? errorText) {
    if (_validation == null) {
      return;
    }

    if (errorText == null) {
      _validation!.markTouched();
      return;
    }

    _validation!.setError(errorText, markTouched: true);
  }

  @override
  void dispose() {
    _subscription?.cancel();
    _subscription = null;
    _validation = null;
    _validationMessages = null;
    super.dispose();
  }
}

/// A mixin for managing the lifecycle of [CurrentTextController]s in a [CurrentState].
///
/// This mixin initializes controllers on the first dependency pass and re-runs
/// [bindCurrentControllers] when the widget updates so controllers can rebind
/// to new properties when needed.
///
/// Must implement [bindCurrentControllers]. This is where you should initialize your [CurrentTextController]s.
mixin CurrentTextControllersLifecycleMixin<TWidget extends CurrentWidget,
    TViewModel extends CurrentViewModel> on CurrentState<TWidget, TViewModel> {
  bool _initializedControllers = false;

  /// Whether the CurrentTextControllers have been initialized. This is used to ensure that the controllers are only initialized once.
  bool get controllersInitialized => _initializedControllers;

  void bindCurrentControllers();

  void _bindOrRebindControllers() {
    bindCurrentControllers();
    _initializedControllers = true;
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    if (!controllersInitialized) {
      _bindOrRebindControllers();
    }
  }

  @override
  void didUpdateWidget(covariant TWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    _bindOrRebindControllers();
  }
}
