import 'dart:async';

import 'package:current/current.dart';
import 'package:current/src/current_exceptions.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// A TextEditingController that is bound to a CurrentProperty.
///
/// Should apply the [CurrentTextControllersLifecycleMixin] mixin to the State of your Widget to manage the lifecycle of the controller and ensure it is properly disposed of.
///
/// Use the factory contructors to create a new instance.
///
/// [CurrentTextController.string], [CurrentTextController.nullableString],
///
/// [CurrentTextController.integer], [CurrentTextController.nullableInteger],
///
/// [CurrentTextController.date], and [CurrentTextController.nullableDate]
///
/// These are provided for convenience when working with common types, but you can also use [CurrentTextController.of] to create a controller for any type.
///
/// When using [CurrentTextController.of], you must provide the fromString and [asString] functions in the [bind] method to specify how to parse the text into the property's type and how to display the property's value as text.
///
/// It listens for changes to the property and updates the text accordingly, and also updates the property when the text changes.
/// You MUST call [bind] to configure the controller. If you do not, the controller will simply act as a normal [TextEditingController].
///
/// When used together with [CurrentFieldValidation], the controller can also:
/// - mark a field as touched when the user edits text
/// - surface parse failures as validation metadata
/// - surface required-value failures for non-nullable fields without defaults
/// - revalidate when the bound property changes externally
///
/// Controller-generated validation issues are configurable through
/// [CurrentTextControllerValidationIssues]. This is important because parse
/// failures and required-value failures are generated by the controller rather
/// than by property-specific validator rules.
///
/// Example usage:
///
///
/// ```dart
///
/// class MyWidgetViewModel extends CurrentViewModel {
///   final name = CurrentStringProperty();
///   final age = CurrentIntProperty();
///   final departureDate = CurrentNullableDateTimeProperty();
///
///   @override
///   Iterable<CurrentProperty> get currentProps => [name, age, departureDate];
/// }
///
/// class _MyWidgetState extends CurrentState<_MyWidgetState, MyWidgetViewModel> with CurrentTextControllersLifecycleMixin {
///
///   final nameController = CurrentTextController.string();
///   final ageController = CurrentTextController.integer();
///   final departureDateController = CurrentTextController.nullableDate();
///
///   @override
///   void bindCurrentControllers() {
///     nameController.bindString(
///       property: viewModel.name,
///       lifecycleProvider: this,
///     );
///     ageController.bindInt(
///       property: viewModel.age,
///       lifecycleProvider: this,
///       defaultValue: 0,
///     );
///     departureDateController.bindDateTime(
///       property: viewModel.departureDate,
///       lifecycleProvider: this,
///       fromString: DateTime.parse,
///     );
///   }
///
///   @override
///   void dispose() {
///     nameController.dispose();
///     ageController.dispose();
///     departureDateController.dispose();
///     super.dispose();
///   }
///
///   @override
///   Widget build(BuildContext context) {
///     return Column(
///       children: [
///         TextField(controller: nameController),
///         TextField(controller: ageController),
///         TextField(controller: departureDateController),
///       ],
///     );
///   }
/// }
/// ```
///
typedef CurrentTextControllerRequiredValueIssueBuilder = CurrentValidationIssue?
    Function();
typedef CurrentTextControllerInvalidValueIssueBuilder = CurrentValidationIssue?
    Function(
  String text,
);
typedef CurrentTextControllerValidationBuilder<T> = CurrentFieldValidation<T>?
    Function(
  CurrentProperty<T> property,
  BuildContext context,
);

/// Builds a [FormFieldValidator] from a [CurrentTextController].
typedef CurrentTextControllerFormValidatorBuilder = FormFieldValidator<String>?;

/// Supplies controller-generated validation issues for [CurrentTextController].
///
/// These issues are only used when a [CurrentFieldValidation] is attached to a
/// controller and the controller itself needs to surface a validation
/// problem that did not come from the property's validator rules.
///
/// Typical examples include generic messages such as "this value is required"
/// or "this input could not be parsed".
///
/// Some concrete scenarios include:
/// - the user entering text that fails parsing for a non-String property
/// - the user clearing a non-nullable field that does not have a default value
///
/// This type exists so library consumers can localize those controller-level
/// problems without forcing the controller to create localized strings inside
/// the core package.
///
/// You can either:
/// - override [CurrentTextController.defaultValidationIssues] once for the app
/// - pass a per-binding [validationIssues] value to [bind], [bindString],
///   [bindInt], or [bindDateTime]
///
/// The builders are called the moment the validation problem occurs.
///
/// ## Example
///
/// ```dart
/// ageController.bindInt(
///   property: viewModel.age,
///   lifecycleProvider: this,
///   validationBuilder: (property, _) => property.createValidation(
///     rules: [
///       (value) => value < 18
///           ? const CurrentValidationIssue(
///               'profile.age.minimum',
///               fallbackMessage: 'Must be at least 18',
///             )
///           : null,
///     ],
///     validateOnPropertyChange: true,
///   ),
///   validationIssues: CurrentTextControllerValidationIssues(
///     requiredValueIssueBuilder: () => const CurrentValidationIssue(
///       'profile.age.required',
///       fallbackMessage: 'Entrez une valeur',
///     ),
///     invalidValueIssueBuilder: (_) => const CurrentValidationIssue(
///       'profile.age.invalid',
///       fallbackMessage: 'Valeur incorrecte',
///     ),
///   ),
/// );
/// ```
final class CurrentTextControllerValidationIssues {
  /// Builder used when a non-nullable field is cleared and no default value is
  /// available.
  ///
  /// Returning `null` suppresses the controller-generated required-value issue.
  final CurrentTextControllerRequiredValueIssueBuilder?
      requiredValueIssueBuilder;

  /// Builder used when text cannot be parsed into the target property type.
  ///
  /// The rejected text is provided so callers can vary the issue if needed.
  /// Returning `null` suppresses the controller-generated parse issue.
  final CurrentTextControllerInvalidValueIssueBuilder? invalidValueIssueBuilder;

  /// Creates a set of controller-generated validation issue builders.
  const CurrentTextControllerValidationIssues({
    this.requiredValueIssueBuilder,
    this.invalidValueIssueBuilder,
  });

  /// Returns the required-value issue, if configured.
  CurrentValidationIssue? requiredValueIssue() =>
      requiredValueIssueBuilder?.call();

  /// Returns the invalid-value issue for the provided [text], if configured.
  CurrentValidationIssue? invalidValueIssue(String text) =>
      invalidValueIssueBuilder?.call(text);
}

/// A [TextEditingController] that keeps a [CurrentProperty] and a text field in
/// sync.
///
/// [CurrentTextController] is intended to remove the repetitive plumbing around
/// reading, formatting, parsing, and writing text-field state when working with
/// [CurrentProperty] values.
///
/// The controller supports:
/// - String bindings to keep controller text in sync with the property's value
/// - non-String bindings through a [fromString] parser
/// - custom display formatting through [asString]
/// - default values for cleared non-nullable fields
/// - optional validation through [CurrentFieldValidation]
/// - localized controller-generated validation issues through
///   [CurrentTextControllerValidationIssues]
///
/// This controller does not replace your field validators. Instead, it fills in
/// the gap between raw text editing and property-level validation by surfacing
/// validation metadata for failures that occur before property-level validation,
/// such as parse errors.
final class CurrentTextController<T> extends TextEditingController {
  /// Global default issues used when a binding does not provide
  /// [CurrentTextControllerValidationIssues] explicitly.
  ///
  /// Can be replaced at startup to provide localized controller-generated
  /// validation issues across the app.
  ///
  /// These defaults are only used for controller-originated validation errors,
  /// such as parse failures and required-value failures. Property validator
  /// rules remain fully controlled by the consumer.
  ///
  /// ## Example
  ///
  /// ```dart
  /// CurrentTextController.defaultValidationIssues =
  ///     CurrentTextControllerValidationIssues(
  ///   requiredValueIssueBuilder: () => const CurrentValidationIssue(
  ///     'form.required',
  ///     fallbackMessage: '値を入力してください',
  ///   ),
  ///   invalidValueIssueBuilder: (_) => const CurrentValidationIssue(
  ///     'form.invalid',
  ///     fallbackMessage: '無効な値です',
  ///   ),
  /// );
  /// ```
  static CurrentTextControllerValidationIssues defaultValidationIssues =
      const CurrentTextControllerValidationIssues(
    requiredValueIssueBuilder: _defaultRequiredValueIssue,
    invalidValueIssueBuilder: _defaultInvalidValueIssue,
  );

  /// The [CurrentProperty] that this controller is bound to. This will be set during initialization in the [bind] method.
  ///
  CurrentProperty<T?>? _property;
  CurrentProperty<T?> get property {
    final boundProperty = _property;

    if (boundProperty == null) {
      throw CurrentTextControllerNotInitializedException<T>();
    }

    return boundProperty;
  }

  /// A function that parses a string into the type of the [CurrentProperty]. This is used to update the property's value when the text changes. This will be set during initialization in the [bind] method. If the [CurrentProperty] is of type String, this function can be omitted and the controller will simply use the text as the property's value.
  ///
  T Function(String text)? _fromString;
  T Function(String text)? get fromString => _fromString;

  /// A function that converts the [CurrentProperty]'s value into a string for display in the text field. This will be set during initialization in the [bind] method. If not provided, it will default to using the property's value's toString() method, or an empty string if the property's value is null.
  ///
  String? Function(T? propertyValue)? _asString;
  String? Function(T? propertyValue)? get asString => _asString;

  /// Optional validation helper associated with the bound [CurrentProperty].
  ///
  /// When provided, this controller will mark the field as touched during user
  /// edits, surface rejected text as validation metadata, and keep the
  /// validation state synchronized with successful property updates.
  ///
  /// This validator must target the same [CurrentProperty] instance that is
  /// passed to [bind]. If it does not, [bind] throws an [ArgumentError].
  CurrentFieldValidation<dynamic>? _validation;
  CurrentFieldValidation<dynamic>? get validation => _validation;

  /// Optional per-binding controller-generated validation issues.
  ///
  /// When null, [defaultValidationIssues] is used.
  ///
  /// Use this when a single field requires different issues than the app-wide
  /// defaults.
  CurrentTextControllerValidationIssues? _validationIssues;
  CurrentTextControllerValidationIssues? get validationIssues =>
      _validationIssues;

  /// An optional default value to use when parsing the text if the [fromString] function fails to parse the text. This is only used for non-String properties. If the [CurrentProperty] is of type String, this can be omitted since parsing will not be performed.
  ///
  StreamSubscription? _subscription;

  /// An optional default value to use when parsing the text if the [fromString] function fails to parse the text. This is only used for non-String properties. If the [CurrentProperty] is of type String, this can be omitted since parsing will not be performed.
  ///
  T? _defaultValue;
  T? get defaultValue => _defaultValue;

  bool get _isNullable => null is T;

  bool _hasDefaultValue = false;
  bool _isSyncingText = false;
  bool _treatTextAsStringValue = false;
  bool _validationSyncScheduled = false;

  /// Whether the controller is currently applying a synchronized text update
  /// from the bound property.
  bool get isSynchronizingText => _isSyncingText;

  CurrentTextControllersLifecycleMixin? _lifecycleProvider;

  CurrentTextController._() {
    addListener(_handleTextChanged);
  }

  /// Factory constructor to create a CurrentTextController for a String property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindString]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<String> string() =>
      CurrentTextController<String>._();

  /// Factory constructor to create a CurrentTextController for a nullable String  property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindString]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<String?> nullableString() =>
      CurrentTextController<String?>._();

  /// Factory constructor to create a CurrentTextController for an integer property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindInt]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<int> integer() => CurrentTextController<int>._();

  /// Factory constructor to create a CurrentTextController for a nullable integer property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindInt]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<int?> nullableInteger() =>
      CurrentTextController<int?>._();

  /// Factory constructor to create a CurrentTextController for a DateTime property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindDateTime]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<DateTime> date() =>
      CurrentTextController<DateTime>._();

  /// Factory constructor to create a CurrentTextController for a nullable DateTime property.
  ///
  /// **IMPORTANT**: You still must call either the [bind] or the [bindDateTime]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<DateTime?> nullableDate() =>
      CurrentTextController<DateTime?>._();

  /// Factory constructor to create a CurrentTextController for a type specified by the generic parameter [T].
  ///
  /// **IMPORTANT**: You still must call either the [bind]
  /// in the [CurrentTextControllersLifecycleMixin.bindCurrentControllers] method to initialize the controller and bind it to a CurrentProperty.
  /// The factory constructor only creates an instance of the controller, but does not configure it in any way.
  static CurrentTextController<T> of<T>() => CurrentTextController<T>._();

  /// Initializes the CurrentTextController by binding it to a CurrentProperty and providing necessary configuration for parsing and displaying the property's value.
  ///
  /// If the CurrentProperty is not of type String, you must provide a fromString function to parse the text into the property's type.
  ///
  /// If it is a Non-Nullable non-String type, you can optionally provide a
  /// [defaultValue]. When the user clears the text field, the controller will
  /// use that explicit default value instead of leaving the property unchanged.
  /// Invalid non-empty text does not throw and does not update the property
  /// until parsing succeeds.
  ///
  /// If the CurrentProperty is of type String, you can omit the fromString function and the controller will simply use the text as the property's value. In this case, providing a defaultValue is not necessary since parsing will not be performed.
  ///
  /// The asString function is optional, but can be used to customize how the property's value is displayed in the text field. If not provided, it will default to using the property's value's toString() method, or an empty string if the property's value is null.
  ///
  /// If [validation] is provided, [validationIssues] can be used to override
  /// the controller-generated validation issues for this binding.
  ///
  /// If [validation] is omitted, the controller will try to discover a
  /// validation already registered against [property] via
  /// [CurrentPropertyValidationExtensions.createValidation].
  ///
  /// If the property does not already have a registered validation,
  /// [validationBuilder] can create one using the current [BuildContext].
  ///
  /// Validation behavior when [validation] is provided:
  /// - user edits mark the field as touched
  /// - parse failures set controller-generated validation metadata
  /// - successful updates re-run the validator against the new property value
  /// - external property changes re-sync the text and revalidate
  ///
  /// If [validationIssues] is omitted, [defaultValidationIssues] is used.
  ///
  /// If a [validation] is supplied for a different property than [property], an
  /// [ArgumentError] is thrown.
  ///
  void bind({
    required CurrentProperty<T?> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    T Function(String text)? fromString,
    String? Function(T? propertyValue)? asString,
    T? defaultValue,
    CurrentFieldValidation<dynamic>? validation,
    CurrentTextControllerValidationBuilder<T?>? validationBuilder,
    CurrentTextControllerValidationIssues? validationIssues,
  }) {
    final treatTextAsStringValue = _isStringProperty(property);
    final resolvedValidation = validation ??
        property.tryGetValidation() ??
        validationBuilder?.call(property, lifecycleProvider.context);

    if (!treatTextAsStringValue && fromString == null) {
      throw ArgumentError.value(
        fromString,
        'fromString',
        'A fromString function is required for non-String CurrentTextController bindings.',
      );
    }

    if (resolvedValidation != null &&
        !identical(resolvedValidation.property, property)) {
      throw ArgumentError.value(
        resolvedValidation,
        'validation',
        'The provided CurrentFieldValidation must target the same CurrentProperty bound to this controller.',
      );
    }

    if (resolvedValidation != null &&
        !property.registeredBindings.contains(resolvedValidation)) {
      property.registerBinding(resolvedValidation);
    }

    if (_matchesBinding(
      property: property,
      lifecycleProvider: lifecycleProvider,
      fromString: fromString,
      asString: asString,
      defaultValue: defaultValue,
      treatTextAsStringValue: treatTextAsStringValue,
      validation: resolvedValidation,
      validationIssues: validationIssues,
    )) {
      return;
    }

    _subscription?.cancel();

    _property = property;
    _fromString = fromString;
    _asString = asString;
    _defaultValue = defaultValue;
    _hasDefaultValue = !_isNullable && defaultValue != null;
    _treatTextAsStringValue = treatTextAsStringValue;
    _lifecycleProvider = lifecycleProvider;
    _validation = resolvedValidation;
    _validationIssues = validationIssues;

    _subscription =
        property.viewModel.addStateChangedListener<CurrentStateChanged>(
      (_) {
        _setText();
        _validation?.validate();
      },
      filter: (event) =>
          event.sourceHashCode == property.sourceHashCode &&
          event is! CurrentValidationChanged,
    );

    _setText();
  }

  /// A convenience method for initializing the controller with properties based on [CurrentProperty<String>]. This is equivalent to calling [bind] with fromString and asString configured for String properties.
  /// If the CurrentProperty is not of type String, this method will throw an exception.
  ///
  /// See [bind] for details on [validation] and [validationIssues].
  ///
  void bindString({
    required CurrentProperty<T> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    String? Function(T? propertyValue)? asString,
    CurrentFieldValidation<T>? validation,
    CurrentTextControllerValidationBuilder<T>? validationBuilder,
    CurrentTextControllerValidationIssues? validationIssues,
  }) {
    (bool isValidType, List<Type> validTypes) validateType(
        CurrentProperty property) {
      final validTypes = [
        CurrentProperty<String>,
        CurrentProperty<String?>,
        CurrentStringProperty,
        CurrentNullableStringProperty
      ];

      // This is done in a verbose way, duplicating the list (unfortunately) to ensure type check safety,
      // guarding against Darts reified generics. Simply checking via `validTypes.any((type) => property.runtimeType == type)`
      // is not guaranteed to behave correctly due to possible type erasure.
      if (property is! CurrentProperty<String> &&
          property is! CurrentProperty<String?> &&
          property is! CurrentStringProperty &&
          property is! CurrentNullableStringProperty) {
        return (false, validTypes);
      }
      return (true, validTypes);
    }

    if (validateType(property) case (false, final validTypes)) {
      throw CurrentTextControllerCurrentPropertyTypeException(
        property,
        'stringController',
        validTypes,
      );
    }

    bind(
      property: property,
      lifecycleProvider: lifecycleProvider,
      asString: asString,
      validation: validation,
      validationBuilder: validationBuilder == null
          ? null
          : (property, context) =>
              validationBuilder(property as CurrentProperty<T>, context),
      validationIssues: validationIssues,
    );
  }

  /// A convenience method for initializing the controller with properties based on [CurrentProperty<int>]. This is equivalent to calling [bind] with fromString and asString configured for int properties.
  /// If the CurrentProperty is not of type int, this method will throw an exception.
  ///
  /// If [fromString] is omitted, [int.parse] is used.
  ///
  /// See [bind] for details on [defaultValue], [validation], and
  /// [validationIssues].
  ///
  void bindInt({
    required CurrentProperty<T> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    T Function(String text)? fromString,
    String? Function(T? propertyValue)? asString,
    T? defaultValue,
    CurrentFieldValidation<T>? validation,
    CurrentTextControllerValidationBuilder<T>? validationBuilder,
    CurrentTextControllerValidationIssues? validationIssues,
  }) {
    (bool isValidType, List<Type> validTypes) validateType(
        CurrentProperty property) {
      final validTypes = [
        CurrentProperty<int>,
        CurrentProperty<int?>,
        CurrentIntProperty,
        CurrentNullableIntProperty
      ];

      // This is done in a verbose way, duplicating the list (unfortunately) to ensure type check safety,
      // guarding against Darts reified generics. Simply checking via `validTypes.any((type) => property.runtimeType == type)`
      // is not guaranteed to behave correctly due to possible type erasure.
      if (property is! CurrentProperty<int> &&
          property is! CurrentProperty<int?> &&
          property is! CurrentIntProperty &&
          property is! CurrentNullableIntProperty) {
        return (false, validTypes);
      }
      return (true, validTypes);
    }

    if (validateType(property) case (false, final validTypes)) {
      throw CurrentTextControllerCurrentPropertyTypeException(
        property,
        'intController',
        validTypes,
      );
    }

    bind(
      property: property,
      lifecycleProvider: lifecycleProvider,
      fromString: fromString ?? (text) => int.parse(text) as T,
      asString: asString,
      defaultValue: defaultValue,
      validation: validation,
      validationBuilder: validationBuilder == null
          ? null
          : (property, context) =>
              validationBuilder(property as CurrentProperty<T>, context),
      validationIssues: validationIssues,
    );
  }

  /// A convenience method for initializing the controller with properties based on [CurrentProperty<DateTime>]. This is equivalent to calling [bind] with fromString and asString configured for DateTime properties.
  /// The [property] must be of type [CurrentProperty<DateTime>], [CurrentDateTimeProperty], or [CurrentNullableDateTimeProperty]. If it is not, this method will throw an exception.
  ///
  /// See [bind] for details on [validation] and [validationIssues].
  ///
  void bindDateTime({
    required CurrentProperty<T> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    required T Function(String text) fromString,
    String? Function(T? propertyValue)? asString,
    T? defaultValue,
    CurrentFieldValidation<T>? validation,
    CurrentTextControllerValidationBuilder<T>? validationBuilder,
    CurrentTextControllerValidationIssues? validationIssues,
  }) {
    (bool isValidType, List<Type> validTypes) validateType(
        CurrentProperty property) {
      final validTypes = [
        CurrentProperty<DateTime>,
        CurrentProperty<DateTime?>,
        CurrentDateTimeProperty,
        CurrentNullableDateTimeProperty
      ];

      // This is done in a verbose way, duplicating the list (unfortunately) to ensure type check safety,
      // guarding against Darts reified generics. Simply checking via `validTypes.any((type) => property.runtimeType == type)`
      // is not guaranteed to behave correctly due to possible type erasure.
      if (property is! CurrentProperty<DateTime> &&
          property is! CurrentProperty<DateTime?> &&
          property is! CurrentDateTimeProperty &&
          property is! CurrentNullableDateTimeProperty) {
        return (false, validTypes);
      }
      return (true, validTypes);
    }

    if (validateType(property) case (false, final validTypes)) {
      throw CurrentTextControllerCurrentPropertyTypeException(
        property,
        'dateController',
        validTypes,
      );
    }

    bind(
      property: property,
      lifecycleProvider: lifecycleProvider,
      fromString: fromString,
      asString: asString ??
          (propertyValue) =>
              (propertyValue as DateTime?)?.toIso8601String() ?? '',
      defaultValue: defaultValue,
      validation: validation,
      validationBuilder: validationBuilder == null
          ? null
          : (property, context) =>
              validationBuilder(property as CurrentProperty<T>, context),
      validationIssues: validationIssues,
    );
  }

  /// Resolves the currently visible validation error for text-field style
  /// widgets that still use `InputDecoration.errorText` directly.
  ///
  /// This keeps the legacy TextField path to a single expression instead of
  /// forcing each widget to inspect touched and validated state manually.
  String? visibleErrorText({
    BuildContext? context,
    CurrentValidationIssueTextResolver? resolver,
  }) {
    final currentValidation = _validation;

    if (currentValidation == null ||
        !currentValidation.hasIssue ||
        !(currentValidation.isTouched || currentValidation.hasValidated)) {
      return null;
    }

    return currentValidation.resolveIssueText(
      context: context,
      resolver: resolver,
    );
  }

  /// Computes the current validation issue for the controller text without
  /// mutating validation state.
  CurrentValidationIssue? previewValidationIssue() {
    return _computeValidationIssueForText();
  }

  /// Synchronizes validation metadata with the controller's current text.
  ///
  /// This is useful for wrapper widgets that need TextField-style validation
  /// behavior outside Flutter's built-in [Form] pipeline.
  void synchronizeValidation({
    bool markTouched = true,
    bool resetTextOnRequiredFailure = true,
  }) {
    if (_property == null) {
      return;
    }

    _syncValidationFromCurrentText(
      resetTextOnRequiredFailure: resetTextOnRequiredFailure,
      markTouched: markTouched,
    );
  }

  /// Creates a stock Flutter [FormField.validator] callback for this
  /// controller.
  ///
  /// Use this with [TextFormField] when you want Current to drive validation
  /// while still using Flutter's native form widgets and
  /// [AutovalidateMode] behavior.
  FormFieldValidator<String>? formValidator({
    BuildContext? context,
    CurrentValidationIssueTextResolver? resolver,
    bool markTouched = true,
  }) {
    final currentValidation = _validation;

    if (currentValidation == null) {
      return null;
    }

    return (_) {
      final issue = _computeValidationIssueForText() ?? currentValidation.issue;
      final shouldSync = markTouched &&
          (!currentValidation.hasValidated ||
              !currentValidation.isTouched ||
              currentValidation.issue != issue);

      if (shouldSync) {
        _scheduleValidationSync(markTouched: markTouched);
      }

      return issue?.resolveText(context: context, resolver: resolver);
    };
  }

  void _setText({bool selectAll = false}) {
    final boundProperty = _property;

    if (boundProperty == null) {
      return;
    }

    final nextText = _asString?.call(boundProperty.value) ??
        boundProperty.value?.toString() ??
        '';

    if (nextText == text) {
      return;
    }

    _isSyncingText = true;

    try {
      value = TextEditingValue(
        text: nextText,
        selection: selectAll && nextText.isNotEmpty
            ? TextSelection(baseOffset: 0, extentOffset: nextText.length)
            : TextSelection.collapsed(offset: nextText.length),
      );
    } finally {
      _isSyncingText = false;
    }
  }

  void _handleTextChanged() {
    final boundProperty = _property;

    if (_isSyncingText || boundProperty == null) {
      return;
    }

    _syncValidationFromCurrentText(resetTextOnRequiredFailure: true);
  }

  CurrentValidationIssue? _computeValidationIssueForText() {
    final currentValidation = _validation;

    if (currentValidation == null) {
      return null;
    }

    final parseResult = _tryParseText(text);

    if (!parseResult.shouldUpdate &&
        text.isEmpty &&
        !_isNullable &&
        !_hasDefaultValue) {
      return _resolvedValidationIssues.requiredValueIssue();
    }

    if (!parseResult.shouldUpdate) {
      return _resolvedValidationIssues.invalidValueIssue(text);
    }

    return currentValidation.issueForValue(parseResult.value);
  }

  void _scheduleValidationSync({required bool markTouched}) {
    if (_validation == null || _validationSyncScheduled) {
      return;
    }

    _validationSyncScheduled = true;

    WidgetsBinding.instance.addPostFrameCallback((_) {
      _validationSyncScheduled = false;

      if (_validation == null || _property == null) {
        return;
      }

      _syncValidationFromCurrentText(
        resetTextOnRequiredFailure: false,
        markTouched: markTouched,
      );
    });
  }

  void _syncValidationFromCurrentText({
    required bool resetTextOnRequiredFailure,
    bool markTouched = true,
  }) {
    final boundProperty = _property;

    if (boundProperty == null) {
      return;
    }

    if (markTouched) {
      _validation?.markTouched();
    }

    final parseResult = _tryParseText(text);

    if (!parseResult.shouldUpdate &&
        text.isEmpty &&
        !_isNullable &&
        !_hasDefaultValue) {
      _setControllerValidationError(
        _resolvedValidationIssues.requiredValueIssue(),
      );

      if (resetTextOnRequiredFailure) {
        _setText(selectAll: true);
      }

      return;
    }

    if (!parseResult.shouldUpdate) {
      _setControllerValidationError(
        _resolvedValidationIssues.invalidValueIssue(text),
      );
      return;
    }

    if (parseResult.value == boundProperty.value) {
      _validation?.validate(markTouched: markTouched);
      return;
    }

    boundProperty.value = parseResult.value;
    _validation?.validate(markTouched: markTouched);
  }

  ({bool shouldUpdate, T? value}) _tryParseText(String text) {
    if (_treatTextAsStringValue) {
      if (text.isEmpty && _isNullable) {
        return (shouldUpdate: true, value: null);
      }

      return (shouldUpdate: true, value: text as T);
    }

    if (text.isEmpty) {
      if (_isNullable) {
        return (shouldUpdate: true, value: null);
      }

      if (_hasDefaultValue) {
        return (shouldUpdate: true, value: _defaultValue);
      }

      return (shouldUpdate: false, value: null);
    }

    if (_fromString == null) {
      return (shouldUpdate: false, value: null);
    }

    try {
      return (shouldUpdate: true, value: _fromString!(text));
    } catch (_) {
      return (shouldUpdate: false, value: null);
    }
  }

  bool _isStringProperty(CurrentProperty property) {
    return property is CurrentProperty<String> ||
        property is CurrentProperty<String?> ||
        property is CurrentStringProperty ||
        property is CurrentNullableStringProperty;
  }

  bool _matchesBinding({
    required CurrentProperty<T?> property,
    required CurrentTextControllersLifecycleMixin lifecycleProvider,
    required T Function(String text)? fromString,
    required String? Function(T? propertyValue)? asString,
    required T? defaultValue,
    required bool treatTextAsStringValue,
    required CurrentFieldValidation<dynamic>? validation,
    required CurrentTextControllerValidationIssues? validationIssues,
  }) {
    return identical(_property, property) &&
        identical(_lifecycleProvider, lifecycleProvider) &&
        identical(_fromString, fromString) &&
        identical(_asString, asString) &&
        identical(_validation, validation) &&
        identical(_validationIssues, validationIssues) &&
        _defaultValue == defaultValue &&
        _hasDefaultValue == (!_isNullable && defaultValue != null) &&
        _treatTextAsStringValue == treatTextAsStringValue;
  }

  CurrentTextControllerValidationIssues get _resolvedValidationIssues =>
      _validationIssues ?? defaultValidationIssues;

  void _setControllerValidationError(CurrentValidationIssue? issue) {
    if (_validation == null) {
      return;
    }

    if (issue == null) {
      _validation!.markTouched();
      return;
    }

    _validation!.setIssue(issue, markTouched: true);
  }

  @override
  void dispose() {
    _subscription?.cancel();
    _subscription = null;
    _validation = null;
    _validationIssues = null;
    _validationSyncScheduled = false;
    super.dispose();
  }

  static CurrentValidationIssue _defaultRequiredValueIssue() {
    return const CurrentValidationIssue.requiredValue(
      fallbackMessage: 'A value is required.',
    );
  }

  static CurrentValidationIssue _defaultInvalidValueIssue(String text) {
    return CurrentValidationIssue.invalidValue(
      fallbackMessage: 'Invalid value.',
      arguments: {'text': text},
    );
  }
}

/// A convenience [TextFormField] wired to a [CurrentTextController].
///
/// This keeps Flutter's native form behavior and [AutovalidateMode] behavior
/// while delegating property synchronization and validation to Current.
class CurrentTextFormField<T> extends StatelessWidget {
  const CurrentTextFormField({
    super.key,
    required this.controller,
    this.validationTextResolver,
    this.autovalidateMode,
    this.decoration = const InputDecoration(),
    this.focusNode,
    this.keyboardType,
    this.textInputAction,
    this.textCapitalization = TextCapitalization.none,
    this.textAlign = TextAlign.start,
    this.style,
    this.readOnly = false,
    this.enabled,
    this.autofocus = false,
    this.obscureText = false,
    this.minLines,
    this.maxLines = 1,
    this.maxLength,
    this.expands = false,
    this.inputFormatters,
    this.onChanged,
    this.onFieldSubmitted,
    this.onTap,
  });

  final CurrentTextController<T> controller;
  final CurrentValidationIssueTextResolver? validationTextResolver;
  final AutovalidateMode? autovalidateMode;
  final InputDecoration decoration;
  final FocusNode? focusNode;
  final TextInputType? keyboardType;
  final TextInputAction? textInputAction;
  final TextCapitalization textCapitalization;
  final TextAlign textAlign;
  final TextStyle? style;
  final bool readOnly;
  final bool? enabled;
  final bool autofocus;
  final bool obscureText;
  final int? minLines;
  final int? maxLines;
  final int? maxLength;
  final bool expands;
  final List<TextInputFormatter>? inputFormatters;
  final ValueChanged<String>? onChanged;
  final ValueChanged<String>? onFieldSubmitted;
  final GestureTapCallback? onTap;

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: controller,
      focusNode: focusNode,
      keyboardType: keyboardType,
      textInputAction: textInputAction,
      textCapitalization: textCapitalization,
      textAlign: textAlign,
      style: style,
      readOnly: readOnly,
      enabled: enabled,
      autofocus: autofocus,
      obscureText: obscureText,
      minLines: minLines,
      maxLines: maxLines,
      maxLength: maxLength,
      expands: expands,
      inputFormatters: inputFormatters,
      decoration: decoration,
      autovalidateMode: autovalidateMode,
      validator: controller.formValidator(
        context: context,
        resolver: validationTextResolver,
      ),
      onChanged: onChanged,
      onFieldSubmitted: onFieldSubmitted,
      onTap: onTap,
    );
  }
}

/// A convenience [TextField] wired to a [CurrentTextController].
///
/// This is useful when you want Current-managed field validation without using
/// Flutter's [Form] widgets. Validation visibility is controlled locally using
/// [AutovalidateMode]-style behaviors.
class CurrentTextField<T> extends StatefulWidget {
  const CurrentTextField({
    super.key,
    required this.controller,
    this.validationTextResolver,
    this.autovalidateMode = AutovalidateMode.disabled,
    this.decoration = const InputDecoration(),
    this.focusNode,
    this.keyboardType,
    this.textInputAction,
    this.textCapitalization = TextCapitalization.none,
    this.textAlign = TextAlign.start,
    this.style,
    this.readOnly = false,
    this.enabled,
    this.autofocus = false,
    this.obscureText = false,
    this.minLines,
    this.maxLines = 1,
    this.maxLength,
    this.expands = false,
    this.inputFormatters,
    this.onChanged,
    this.onSubmitted,
    this.onTap,
  });

  final CurrentTextController<T> controller;
  final CurrentValidationIssueTextResolver? validationTextResolver;
  final AutovalidateMode autovalidateMode;
  final InputDecoration decoration;
  final FocusNode? focusNode;
  final TextInputType? keyboardType;
  final TextInputAction? textInputAction;
  final TextCapitalization textCapitalization;
  final TextAlign textAlign;
  final TextStyle? style;
  final bool readOnly;
  final bool? enabled;
  final bool autofocus;
  final bool obscureText;
  final int? minLines;
  final int? maxLines;
  final int? maxLength;
  final bool expands;
  final List<TextInputFormatter>? inputFormatters;
  final ValueChanged<String>? onChanged;
  final ValueChanged<String>? onSubmitted;
  final GestureTapCallback? onTap;

  @override
  State<CurrentTextField<T>> createState() => _CurrentTextFieldState<T>();
}

class _CurrentTextFieldState<T> extends State<CurrentTextField<T>> {
  StreamSubscription<CurrentValidationChanged>? _validationSubscription;
  FocusNode? _ownedFocusNode;
  bool _hasInteracted = false;
  bool _hasLostFocusOnce = false;
  bool _revalidateOnInteractionAfterError = false;
  String _lastObservedText = '';

  FocusNode get _focusNode => widget.focusNode ?? _ownedFocusNode!;

  @override
  void initState() {
    super.initState();
    _lastObservedText = widget.controller.text;
    _attachFocusNode();
    widget.controller.addListener(_handleControllerChanged);
    _subscribeToValidationChanges();
    _scheduleAlwaysValidationIfNeeded();
  }

  @override
  void didUpdateWidget(covariant CurrentTextField<T> oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (!identical(oldWidget.controller, widget.controller)) {
      oldWidget.controller.removeListener(_handleControllerChanged);
      widget.controller.addListener(_handleControllerChanged);
      _lastObservedText = widget.controller.text;
      _subscribeToValidationChanges();
    }

    if (!identical(oldWidget.focusNode, widget.focusNode)) {
      _detachFocusNode(oldWidget.focusNode);
      _attachFocusNode();
    }

    if (oldWidget.autovalidateMode != widget.autovalidateMode) {
      _scheduleAlwaysValidationIfNeeded();
    }
  }

  @override
  void dispose() {
    widget.controller.removeListener(_handleControllerChanged);
    _validationSubscription?.cancel();
    _detachFocusNode(widget.focusNode);
    super.dispose();
  }

  void _attachFocusNode() {
    if (widget.focusNode == null) {
      _ownedFocusNode ??= FocusNode();
    }

    _focusNode.addListener(_handleFocusChanged);
  }

  void _detachFocusNode(FocusNode? explicitFocusNode) {
    final focusNode = explicitFocusNode ?? _ownedFocusNode;

    if (focusNode == null) {
      return;
    }

    focusNode.removeListener(_handleFocusChanged);

    if (explicitFocusNode == null) {
      focusNode.dispose();
      _ownedFocusNode = null;
    }
  }

  void _subscribeToValidationChanges() {
    _validationSubscription?.cancel();

    final validation = widget.controller.validation;

    if (validation == null) {
      return;
    }

    _validationSubscription = validation.property.viewModel
        .addStateChangedListener<CurrentValidationChanged>(
      (_) {
        if (!mounted) {
          return;
        }

        if (validation.hasIssue) {
          _revalidateOnInteractionAfterError = true;
        }

        setState(() {});
      },
      filter: (event) =>
          event.validationSourceHashCode == validation.validationSourceHashCode,
    );
  }

  void _scheduleAlwaysValidationIfNeeded() {
    if (widget.autovalidateMode != AutovalidateMode.always) {
      return;
    }

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted || widget.autovalidateMode != AutovalidateMode.always) {
        return;
      }

      widget.controller.synchronizeValidation(
        markTouched: false,
        resetTextOnRequiredFailure: false,
      );

      if (mounted) {
        setState(() {});
      }
    });
  }

  void _handleControllerChanged() {
    final textChanged = widget.controller.text != _lastObservedText;
    _lastObservedText = widget.controller.text;

    if (!mounted) {
      return;
    }

    if (widget.controller.isSynchronizingText || !textChanged) {
      setState(() {});
      return;
    }

    if (_focusNode.hasFocus) {
      _hasInteracted = true;
    }

    switch (widget.autovalidateMode) {
      case AutovalidateMode.disabled:
        setState(() {});
        break;
      case AutovalidateMode.always:
        widget.controller.synchronizeValidation(markTouched: true);
        setState(() {});
        break;
      case AutovalidateMode.onUserInteraction:
        widget.controller.synchronizeValidation(markTouched: true);
        setState(() {});
        break;
      case AutovalidateMode.onUnfocus:
        setState(() {});
        break;
      case AutovalidateMode.onUserInteractionIfError:
        if (_revalidateOnInteractionAfterError ||
            (widget.controller.validation?.hasIssue ?? false)) {
          widget.controller.synchronizeValidation(markTouched: true);
        }
        setState(() {});
        break;
    }
  }

  void _handleFocusChanged() {
    if (!mounted) {
      return;
    }

    if (!_focusNode.hasFocus) {
      _hasLostFocusOnce = true;

      if (widget.autovalidateMode == AutovalidateMode.onUnfocus) {
        widget.controller.synchronizeValidation(markTouched: true);
      }
    }

    setState(() {});
  }

  String? _resolvedErrorText(BuildContext context) {
    final resolver = widget.validationTextResolver;

    switch (widget.autovalidateMode) {
      case AutovalidateMode.disabled:
        return widget.controller.visibleErrorText(
          context: context,
          resolver: resolver,
        );
      case AutovalidateMode.always:
        return widget.controller.visibleErrorText(
          context: context,
          resolver: resolver,
        );
      case AutovalidateMode.onUserInteraction:
        return _hasInteracted
            ? widget.controller.visibleErrorText(
                context: context,
                resolver: resolver,
              )
            : null;
      case AutovalidateMode.onUnfocus:
        return _hasLostFocusOnce
            ? widget.controller.visibleErrorText(
                context: context,
                resolver: resolver,
              )
            : null;
      case AutovalidateMode.onUserInteractionIfError:
        return _revalidateOnInteractionAfterError ||
                (widget.controller.validation?.hasIssue ?? false)
            ? widget.controller.visibleErrorText(
                context: context,
                resolver: resolver,
              )
            : null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: widget.controller,
      focusNode: _focusNode,
      keyboardType: widget.keyboardType,
      textInputAction: widget.textInputAction,
      textCapitalization: widget.textCapitalization,
      textAlign: widget.textAlign,
      style: widget.style,
      readOnly: widget.readOnly,
      enabled: widget.enabled,
      autofocus: widget.autofocus,
      obscureText: widget.obscureText,
      minLines: widget.minLines,
      maxLines: widget.maxLines,
      maxLength: widget.maxLength,
      expands: widget.expands,
      inputFormatters: widget.inputFormatters,
      decoration: widget.decoration.copyWith(
        errorText: _resolvedErrorText(context),
      ),
      onChanged: widget.onChanged,
      onSubmitted: widget.onSubmitted,
      onTap: widget.onTap,
    );
  }
}

/// A mixin for managing the lifecycle of [CurrentTextController]s in a [CurrentState].
///
/// This mixin initializes controllers on the first dependency pass and re-runs
/// [bindCurrentControllers] when the widget updates so controllers can rebind
/// to new properties when needed.
///
/// Must implement [bindCurrentControllers]. This is where you should initialize your [CurrentTextController]s.
mixin CurrentTextControllersLifecycleMixin<TWidget extends CurrentWidget,
    TViewModel extends CurrentViewModel> on CurrentState<TWidget, TViewModel> {
  bool _initializedControllers = false;

  /// Whether the CurrentTextControllers have been initialized. This is used to ensure that the controllers are only initialized once.
  bool get controllersInitialized => _initializedControllers;

  void bindCurrentControllers();

  void _bindOrRebindControllers() {
    bindCurrentControllers();
    _initializedControllers = true;
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    if (!controllersInitialized) {
      _bindOrRebindControllers();
    }
  }

  @override
  void didUpdateWidget(covariant TWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    _bindOrRebindControllers();
  }
}
