name: Validate Docs

on:
  pull_request:
    paths:
      - "lib/**"
      - "README.md"
      - "pubspec.yaml"
      - "validateVersions.sh"

  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "README.md"
      - "pubspec.yaml"
      - "validateVersions.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Validate docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: dart doc
      - run: ./validateVersions.sh
