name: "CI: Library"

on:
  pull_request:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/validate_library.yml"

  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/validate_examples.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter analyze lib
      - run: flutter test
      - run: dart pub publish --dry-run
