name: "CI: Examples"

on:
  pull_request:
    paths:
      - "example/**"
      - "lib/**"

  push:
    branches:
      - main
    paths:
      - "example/**"
      - "lib/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    name: Validate examples
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
